# Stage 1: Build the application
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

# Copy the project files and solution file
COPY ["PayhouseDragonFly.sln", "./"]
COPY . .

# Build the application
RUN dotnet build "PayhouseDragonFly.sln" -c Release -o /app/build

# Stage 2: Create the final image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final
WORKDIR /app

# Copy the published application from the build stage
COPY --from=build /app/publish .

# Expose the port
EXPOSE 80

# Run the application
ENTRYPOINT ["dotnet", "PayhouseDragonFly.API.dll"]
