# Use the base image for building
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# Set the working directory
WORKDIR /src

# Copy the project files and solution file
COPY ["PayhouseDragonFly.sln", "./"]
COPY ["PayhouseDragonFly.API/PayhouseDragonFly.API.csproj", "PayhouseDragonFly.API/"]
COPY ["PayhouseDragonFly.CORE/PayhouseDragonFly.CORE.csproj", "PayhouseDragonFly.CORE/"]
COPY ["PayhouseDragonFly.INFRASTRUCTURE/PayhouseDragonFly.INFRASTRUCTURE.csproj", "PayhouseDragonFly.INFRASTRUCTURE/"]

# Restore dependencies
RUN dotnet restore

# Copy the rest of the application code
COPY . .

# Build the application
RUN dotnet build "PayhouseDragonFly.sln" -c Release -o /app/build

# Publish the application
RUN dotnet publish "PayhouseDragonFly.sln" -c Release -o /app/publish

# Use the base image for the final image
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS final

# Set the working directory
WORKDIR /app

# Copy the published application from the build stage
COPY --from=build /app/publish .

# Expose the port
EXPOSE 80

# Run the application
ENTRYPOINT ["dotnet", "PayhouseDragonFly.API.dll"]
